services:
  # Main web service (backend + frontend)
  - type: web
    name: whatsapp-shopify-app
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: FRONTEND_URL
        value: https://whatsapp-shopify-app.onrender.com
      - key: CORS_ORIGIN
        value: https://whatsapp-shopify-app.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_WEBHOOK_SECRET
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false
      - key: WHATSAPP_WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: N8N_BASE_URL
        sync: false
      - key: N8N_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
    healthCheckPath: /health
    
databases:
  # MongoDB database (optional - can use Atlas instead)
  - name: whatsapp-shopify-db
    databaseName: whatsapp_shopify
    user: app_user 